import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata = {
  title: 'Privacy Policy — Invonaut',
  description: 'How Invonaut collects, uses, and protects your personal data.',
}

const EFFECTIVE_DATE = 'June 1, 2025'

const sections = [
  {
    title: 'What we collect',
    body: `We collect information you provide when you create an account (name, email address, business name), 
    and information generated by your use of the platform (invoices, client records, expenses, time entries, 
    contracts, and payment records). We also collect basic usage data to improve the product — pages visited, 
    features used, and error events.`,
  },
  {
    title: 'How we use your data',
    body: `Your data is used to operate Invonaut: to run automations on your behalf (invoice follow-ups, 
    contract reminders, cash flow calculations), to generate AI-powered insights, and to send you emails 
    related to your account. We do not sell your data to any third party. We do not use your financial data 
    for advertising.`,
  },
  {
    title: 'Third-party services',
    body: `Invonaut uses the following services to operate: Supabase (database and authentication), Stripe 
    (payment processing), Resend (transactional email), OpenAI (AI features), Plaid (bank connectivity, 
    where enabled), and Vercel (hosting). Each of these services processes data only as necessary to operate 
    their respective functions. Links to their privacy policies are available on their respective websites.`,
  },
  {
    title: 'Data storage and security',
    body: `Your data is stored in the United States on Supabase-managed infrastructure. We use 
    row-level security to ensure that your data is accessible only to your authenticated account. 
    Passwords are never stored in plaintext. All traffic is encrypted in transit over HTTPS. 
    Stripe handles all payment card data and Invonaut never stores card details directly.`,
  },
  {
    title: 'Your rights',
    body: `You may request a full export of your data at any time by contacting us. You may delete your 
    account at any time — doing so removes your personal profile and access credentials. Invoice and 
    payment records may be retained for a short period to comply with financial recordkeeping requirements 
    before permanent deletion. You may also request correction of inaccurate data.`,
  },
  {
    title: 'Cookies',
    body: `Invonaut uses a small number of cookies strictly necessary to operate the service — session 
    authentication and referral tracking for the affiliate programme. We do not use advertising cookies, 
    tracking pixels, or third-party analytics cookies.`,
  },
  {
    title: 'Communications',
    body: `By creating an account, you consent to receiving transactional emails related to your account 
    (invoices, contract reminders, weekly summaries, billing receipts). You may disable most 
    automated emails in your account settings. We do not send marketing emails without explicit consent.`,
  },
  {
    title: 'Changes to this policy',
    body: `If we make material changes to this policy, we will notify you by email and update the 
    effective date. Continued use of the platform after changes are notified constitutes acceptance 
    of the revised policy.`,
  },
  {
    title: 'Contact',
    body: `For privacy-related questions or data requests, email us at kamo@invonaut.app. 
    We aim to respond within 5 business days.`,
  },
]

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="border-b border-gray-100 sticky top-0 z-10 bg-white/95 backdrop-blur-md">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <img src="/invonaut-logo.png" alt="Invonaut" className="w-7 h-7 rounded-full" />
            <span className="text-base font-black tracking-tight text-gray-900">Invonaut</span>
          </Link>
          <Link href="/" className="inline-flex items-center gap-1.5 text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
            <ArrowLeft className="w-3.5 h-3.5" />Back
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <p className="text-xs font-bold text-[#0055FF] uppercase tracking-widest mb-3">Legal</p>
          <h1 className="text-4xl font-black text-gray-900 tracking-tight mb-4" style={{ fontFamily: "'Fraunces', serif", letterSpacing: '-.03em' }}>
            Privacy Policy
          </h1>
          <p className="text-sm text-gray-500 font-medium">
            Effective date: {EFFECTIVE_DATE} · Invonaut is operated by Kamo Motelle.
          </p>
        </div>

        {/* Intro */}
        <div className="bg-[#F8FAFF] border border-gray-100 rounded-2xl p-6 mb-10">
          <p className="text-sm text-gray-700 font-medium leading-relaxed">
            Invonaut is a business operations platform. We handle financial data on your behalf and take 
            that responsibility seriously. This policy explains what we collect, why we collect it, and how 
            we protect it. We've written it plainly — no legalese where plain English works.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-10">
          {sections.map((s, i) => (
            <div key={i} className="border-b border-gray-50 pb-10 last:border-0 last:pb-0">
              <h2 className="text-base font-black text-gray-900 mb-3">{s.title}</h2>
              <p className="text-sm text-gray-600 font-medium leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>

        {/* Footer links */}
        <div className="mt-16 pt-8 border-t border-gray-100 flex flex-wrap gap-6 text-xs text-gray-400 font-medium">
          <Link href="/terms"   className="hover:text-gray-700 transition-colors">Terms of Service</Link>
          <Link href="/help"    className="hover:text-gray-700 transition-colors">Help Center</Link>
          <Link href="/pricing" className="hover:text-gray-700 transition-colors">Pricing</Link>
          <span>© {new Date().getFullYear()} Invonaut</span>
        </div>
      </div>
    </div>
  )
}
